FROM node:20.17.0-alpine

RUN apk add --no-cache libc5-compat
    

WORKDIR /app

COPY package*.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

FROM base as build

COPY . .

RUN pnpm run build

EXPOSE 3000

FROM build as production

ENV NODE_ENV=production

WORKDIR /app

COPY --from=build /app/package*.json /app/pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile --production

COPY --from=build /app/dist ./dist

CMD ["pnpm", "run", "node", "dist/main"]