FROM node:20.17.0-alpine

WORKDIR /app

# Копируем только package.json для установки зависимостей
COPY package*.json ./

# Устанавливаем зависимости через npm (не pnpm)
RUN npm install

# Остальной код не копируем - используем volume из compose
EXPOSE 3000

# Команда запуска из docker-compose.yml
CMD ["npm", "run", "start:dev"]